/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package spriteviewer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author gustavo
 */
public class PanelPreview extends javax.swing.JPanel{
   
    private Graphics2D graphics2D;
    private BufferedImage buffer;
    
    private BufferedImage image;
    
    private int qtdAnimation = 1;
    private int qtdFrame = 1;
    
    private int currentFrame = 0;
    private int currentAnimation = 1;
    
    private float speedFrame = 0;
    private float timerFrame = 0;
    
    private int width; 
    private int height;
    private float zoom;
    private int marginX;
    private int marginY;
    
    /**
     * Creates new form PanelPreview
     */
    public PanelPreview() {
        initComponents();
    }
    
    public void render(){
        if(graphics2D != null){
            int sx1 = currentFrame*width;
            int sx2 = sx1+width;
            int sy1 = (currentAnimation-1)*height;
            int sy2 = sy1+height;
            
            graphics2D.drawImage(image, 0, 0, (int)(width*zoom), (int)(height*zoom), sx1, sy1, sx2, sy2, null);
        }
    }
    
    public void update(int difTime){
        timerFrame+=difTime;
        currentFrame = (int)(timerFrame/speedFrame)%qtdFrame;
    }
    
    public void prepareFrame(){
        if(image != null){
            width = image.getWidth()/qtdFrame;
            height = image.getHeight()/qtdAnimation;

            buffer = new BufferedImage((int)(width*zoom), (int)(height*zoom), BufferedImage.TYPE_4BYTE_ABGR);
            if(buffer != null){
                graphics2D = (Graphics2D) buffer.getGraphics();
                graphics2D.setBackground(getBackground());
            }
            
            setPreferredSize(new Dimension(buffer.getWidth(), buffer.getHeight()));
            revalidate();
            
            marginX = (getWidth() - buffer.getWidth()) / 2;
            marginY = (getHeight()- buffer.getHeight()) / 2;
            if(marginX < 0)
                marginX = 0;
            if(marginY < 0)
                marginY = 0;
        }
    }

    @Override
    final public void paintComponent(Graphics g){
        super.paintComponent(g);
        render();
        if(buffer != null){
            g.drawImage(buffer, marginX, marginY, null);
            graphics2D.clearRect(0, 0, buffer.getWidth(), buffer.getHeight());
        }
    }

    
    public void setImage(BufferedImage image){
        if(image != null){
            this.image = image;
        }
    }
    
    public void setSpeedFrame(int fps) {
        this.speedFrame = 1000f/fps;
    }
    
    public void setZoom(int value) {
        this.zoom = value/100f;
    }
    
    public void setQtdAnimation(int qtdAnimation) { this.qtdAnimation = qtdAnimation; }
    public void setQtdFrame(int qtdFrame) { this.qtdFrame = qtdFrame; }
    public void setCurrentAnimation(int currentAnimation) { this.currentAnimation = currentAnimation; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
